### ISSUE TITLE
您好请问代码什么时候会公开呢

### ISSUE THREAD

**Issue by Younger330** [Whileherham/CalibratedTeacher#3]
非常感谢你们的工作！请问你们的代码什么时候会公开呢，这对我们的工作有很大的帮助，是否可以提前先给我发一份代码呢

**Comment by somnusyyy** [comment]
我的邮箱是：fy1999xu@gmail.com

**Comment by WuChuhan** [comment]
请问您收到code了吗？

**Comment by somnusyyy** [comment]
您好 没有收到代码

**Comment by somnusyyy** [comment]
> ###
> **[somnusyyy](/somnusyyy) ** commented [Jul 17, 2023](#issuecomment-1637521243)
您好 我没有收到

**Comment by somnusyyy** [comment]
> 请问您收到code了吗？

您好 我没有收到

**Comment by zhang-weii** [comment]
请问收到code了吗？
